// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzgBBSXLuk9kr1-da1Gf2SjJ1QmHXEjKc',
    appId: '1:269758604029:web:d3efbec571aa7cbac29494',
    messagingSenderId: '269758604029',
    projectId: 'whatbytes-af8c7',
    authDomain: 'whatbytes-af8c7.firebaseapp.com',
    storageBucket: 'whatbytes-af8c7.firebasestorage.app',
    measurementId: 'G-JPHC0D1XKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAz3GZlBDiamf0t3VcO_C1p-RCrJCAVDg',
    appId: '1:269758604029:android:69f0cbcbe8d75bb3c29494',
    messagingSenderId: '269758604029',
    projectId: 'whatbytes-af8c7',
    storageBucket: 'whatbytes-af8c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD_W9fWDyQDXkYgC3sEtLIfGicrDZGGkk',
    appId: '1:269758604029:ios:8a879e91224007d3c29494',
    messagingSenderId: '269758604029',
    projectId: 'whatbytes-af8c7',
    storageBucket: 'whatbytes-af8c7.firebasestorage.app',
    iosBundleId: 'com.example.whatbytes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD_W9fWDyQDXkYgC3sEtLIfGicrDZGGkk',
    appId: '1:269758604029:ios:8a879e91224007d3c29494',
    messagingSenderId: '269758604029',
    projectId: 'whatbytes-af8c7',
    storageBucket: 'whatbytes-af8c7.firebasestorage.app',
    iosBundleId: 'com.example.whatbytes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzgBBSXLuk9kr1-da1Gf2SjJ1QmHXEjKc',
    appId: '1:269758604029:web:9094f2e5066438c8c29494',
    messagingSenderId: '269758604029',
    projectId: 'whatbytes-af8c7',
    authDomain: 'whatbytes-af8c7.firebaseapp.com',
    storageBucket: 'whatbytes-af8c7.firebasestorage.app',
    measurementId: 'G-1XV2SR07SQ',
  );
}
